version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tax-consultant-backend-dev
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SESSION_SECRET=${SESSION_SECRET:-dev-session-secret}
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - backend_cache:/app/__pycache__
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - tax-consultant-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: tax-consultant-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - tax-consultant-network

networks:
  tax-consultant-network:
    driver: bridge

volumes:
  backend_cache:
    driver: local